#!/bin/sh
. /etc/nap.conf

ip=`echo $1 | sed -e 's/[^0-9\.]*//g'`
if [ "$ip" = "" ]
then
	echo error no ip address
	return
fi
if [ "$sendport" = "" ] || [ "$recvport" = "" ] || [ $sendport -lte 0 ] || [ $recvport -lte 0 ]
then
	echo error missing send or receive port
	return
fi

response=`wget -q -O - "http://$ip/connect.cgi?send=$sendport&recv=$recvport"`
if [ "$response" = "CONNECTED" ]
	naprtpsend $sendport &
	naprtprecv $recvport &
else 
	echo ERROR
fi
echo $response
