#!/bin/sh
. /etc/nap.conf
memodir=`getmemodir`
memo=$1
if [ -f "$memodir/$1" ] 
then 
	aplay -q -f cd "$memodir/$memo"
fi
memounticked=`echo "$memo" | sed 's/^+//'`
if [ "$memo" != "$memounticked" ]
then
	mv "$memodir/$memo" "$memodir/$memounticked"
fi

true
