#!/bin/sh
. /etc/nap.conf

if [[ -f "$1" ]]
then
	ln -s "$1" "$napshared"
	if [[ $? = 0 ]]
	then
		echo shared 1 item
	fi
else 
	list=`getmusiclist "$1"`
	for item in $list
	do
		ln -s "$1" "$napshared"
	done
	echo shared `echo "$list" | wc -l` items
fi
	
