#!/bin/sh
. /etc/nap.conf

if [[ -f "$1" ]]
then
	sharename=`echo "$1" | sed -e 's#/# #g' -e 's/  */ /g'`
	ln -s "$1" "$napshared/links/$sharename"
	if [[ $? = 0 ]]
	then
		echo shared 1 item
	fi
else 
	IFS=$(echo -en "\n\b")
	list=`getmusiclist "$1"`
	for item in $list
	do
		sharename=`echo "$item" | sed -e 's#/# #g' -e 's/  */ /g'`
		ln -s "$item" "$napshared/links/$sharename"
	done
	echo shared `echo "$list" | wc -l` items
fi
	
