#!/bin/sh
# this should be run periodically from another process
# typically this would be run from the launcher

. /etc/nap.conf

newmemos=`newmemos`

if [ "$1" != "" ] && [ $1 -gt 0 ] 
then
	timeout=$1
else
	timeout=150
fi

if [ $newmemos -gt 0 ]
then
	ledblink -m$newmemos -t$timeout
fi
