#!/bin/sh
# usage naprtpsend {ip} {port} [x86]
# must be careful to avoid overruns 
PATH=".:$PATH"
if [ "$3" = "" ] 
then
	ext=arm
else 
	ext=$3
fi
if [ "$1" = "" ] || [ "$2" = "" ]
then
	echo need ip and port
	return
fi
arecord -f cd -r 4000 --buffer-time=20000000 -t raw | rtpsend-$ext - $1 $2

