######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 30 20:54:05 2011
######################################################################

TEMPLATE = app
TARGET = intercom
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += intercom.h
FORMS += intercom.ui
SOURCES += intercom.cpp main.cpp
