#!/bin/sh
# use this script to get nap configuration paramters in other programs
source /etc/nap.conf
case $1 in
napdata)
	echo $napdata
;;
napshared)
	echo $napshared
;;
naplistenerip)
	echo 225.0.0.`cat "$napdata/naplistenerip" 2>/dev/null`
;;
naplistenerport)
	cat "$napdata/naplistenerport" 2>/dev/null
;;
name)
	cat "$napdata/name" 2>/dev/null
;;
password)
	cat "$napdata/password" 2>/dev/null
;;
esac
