######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 30 20:54:05 2011
######################################################################

TEMPLATE = app
TARGET = intercom-control
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += 'intercom-control.h'
FORMS += 'intercom-control.ui'
SOURCES += 'intercom-control.cpp' main.cpp
