######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 22 23:38:52 2011
######################################################################

TEMPLATE = app
TARGET = memos
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += memos.h
FORMS += memos.ui
SOURCES += main.cpp memos.cpp
