######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 30 20:54:05 2011
######################################################################

TEMPLATE = app
TARGET = intercom-confirm
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += 'intercom-confirm.h'
FORMS += 'intercom-confirm.ui'
SOURCES += 'intercom-confirm.cpp' main.cpp
