######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 30 22:14:15 2011
######################################################################

TEMPLATE = subdirs
TARGET = intercom-confirm

# Directories
SOURCE += main.cpp
