######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 21 09:47:51 2011
######################################################################

TEMPLATE = app
TARGET = launcher
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
FORMS += dialogconfig.ui launcher.ui
SOURCES += periodicthread.cpp dialogconfig.cpp launcher.cpp main.cpp
HEADERS += periodicthread.h dialogconfig.h launcher.h
