######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 21 09:47:51 2011
######################################################################

TEMPLATE = app
TARGET = launcher
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += launcher.ui
SOURCES += launcher.cpp main.cpp
HEADERS += launcher.h 
