######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 07:41:11 2012
######################################################################

TEMPLATE = app
TARGET = player
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += player.ui
