######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 21 22:29:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MusicList.h PlayerWindow.h
FORMS += gui_MainPlay.ui gui_PlaylistCreate.ui
SOURCES += main.cpp MusicList.cpp PlayerWindow.cpp
