#!/bin/sh
# this is a very crude way to do this which assumes we aplay and arecord are only
# being used for this purpose
killall rtpsend-arm
killall rtpsend-x86
killall rtprecv-arm
killall rtprecv-x86
killall aplay
killall arecord
killall naprtpsend
killall naprtprecv
if [ "$1" != "" ] 
then
	wget -q -O - "http://$1/disconnect.cgi"
fi
